#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) Christof Schulze <christof@christofschulze.com>. All Rights Reserved.
#

if [[ -z $WAN ]] || [[ -z $MAXCONNECTIONS ]] || [[ -z $BROKERPORT ]] ||
   [[ -z $STARTPORT ]] || [[ -z $ENDPORT ]] || [[ -z $BABELPORT ]] || [[ -z $WG ]]
   [[ -z $MTU ]] || [[ -z $PRIVATEKEY ]] || [[ -z $L3ROAMDSOCK ]]
then
  if [[ -f /etc/wg-broker/config ]]; then
    . /etc/wg-broker/config
  else
    echo "No such file /etc/wg-broker/config. Exiting" >&2 
    exit 1
  fi
fi

EXITING=""

[[ -f $PRIVATEKEY ]] || {
  echo expecting to find wg secret key in $PRIVATEKEY >&2
  exit 1
}
set -x

cleanup() {
  EXITING=true
  rm -f /tmp/wg-broker
  for i in $(get_wg_interfaces)
  do
    del_interface ${i}
  done
  exit 0
}

trap cleanup exit

get_wg_interfaces() {
    $WG show interfaces |sed 's/ /\n/g'|grep babel-wg-
}

get_connection_count() {
    interfaces=( $(get_wg_interfaces) )
    echo ${#interface[@]}
}

get_port() {
    $WG show ${1:-all} listen-port
}

port_is_assigned() {
    get_port | grep -q "$1"
}

find_free_port() {
    local port=$((STARTPORT + $RANDOM%1000)) # adding RANDOM to  not assign ports sequentially and save some time in below loop
    local sport=$port #

    while $(port_is_assigned $port)
    do
	port=$((port+1))
	[[ $port -eq $ENDPORT ]] && port=$STARTPORT
	[[ $port -eq $sport ]] &&
	{
	  echo 0
	  return
	}
    done

    echo $port
}

add_interface() {
    local newdevice="$1"
    local freeport="$2"
    local public_key="$3"
    local rport="$4"
    local remoteip="$5"

    ip link add dev $newdevice type wireguard
    ip link set multicast on mtu $MTU dev $newdevice
    devicenumber="${ifname##*-}"
    ip a a fe80::${devicenumber}/64 dev $newdevice

    $WG set $newdevice private-key $PRIVATEKEY listen-port $freeport peer $public_key endpoint $remoteip:$rport allowed-ips ::/0
    # ip6tables -A INPUT -i $newdevice -p udp --dport 6696 -j ACCEPT
    # ip6tables -A INPUT -i $WAN -p udp --dport $freeport -j ACCEPT
    # iptables -A INPUT -i $WAN -p udp --dport $freeport -j ACCEPT
    ip link set up dev $newdevice
    echo add_meshif "$1" | socat - unix:$L3ROAMDSOCK
    echo interface $newdevice | timeout 0.2 nc ::1 $BABELPORT >/dev/null
}

del_interface() {
  ip link show "$1" >/dev/null 2>&1 && 
  {
    echo del_meshif "$1" | socat - unix:$L3ROAMDSOCK
    ip link del "$1"
    echo flush interface $1 | timeout 0.2 nc ::1 $BABELPORT
  } >&2
}

nic_namegen() {
    local number=1

    while $(get_wg_interfaces|grep -q babel-wg-$number)
    do
	((number+=1))
    done
    echo "babel-wg-$number"
}

prune_ifs() {
    local interface="$1"

    # delete interface if its peers last_handshake is > 10 Minutes ago
    #	if $($WG show $interface| sed ':a;/^  /{N;s/\n//;ba}'|sed 's/peer:/\npeer/g'|grep peer|grep -qE "[1-5][0-9] minutes")
    #	then
    lhandshake=$($WG show $interface latest-handshakes|awk '{print $2}')

    if [[ $lhandshake -gt 0 ]] && [[ $(( $(date +%s) - lhandshake))  -gt 600 ]]
    then
	del_interface $interface
    fi

    if [[ $( $WG show $interface peers | wc -l ) -eq 0 ]]
    then
	del_interface $interface
    fi
}

find_if() {
    local peer="$1"

    for i in $(get_wg_interfaces)
    do
	if wg show $i peers |grep -q $peer
	then
	    echo $i
	    return
	fi
    done
}

handle_connection() {
    read -r REPLY
    # echo read from client: $REPLY >&2
    jq -r ".localport" <<< "$REPLY" >/dev/null 2>&1 || return 1
    local pkey=$(jq -r ".pubkey" <<<"$REPLY")

    local rport=$(jq -r ".localport" <<< "$REPLY")

    if [[ -n $pkey ]] && [[ -n $rport ]]
    then
	[[ "$rport" =~ [0-9]+ ]] || 
	{
	    echo invalid port >&2
	    return
	}

	if [[ ! $(base64 -d <<<"$pkey" 2>/dev/null |wc -c) -eq 32 ]]
	then
	    echo "invalid public key" >&2
	    return
	fi

	ifname=$(find_if $pkey)

	if [[ -z $ifname ]]
	then
	    port=$(find_free_port)
	    if [[ $port -eq 0 ]]
	    then
	      # SERVER FULL
	      echo "NOT handling the current connection - the server is full." >&2
	    fi
	    ifname=$(nic_namegen)
	else
	    port=$(wg show $ifname listen-port)
	fi

	success=0
	if [[ $port -eq 0 ]] || [[ $(get_connection_count) -gt $MAXCONNECTIONS ]]
	then
	    response="{\"version\":1, \"error\": { \"code\":1, \"reason\": \"Server is not accepting additional connections\"} }"
	else
	    response="{\"version\":1, \"port\": $port}"
	    success=1
	fi

	echo "working on $ifname, write to client: $response"  >&2
	del_interface $ifname
	[[ $success == "1" ]] && add_interface $ifname $port $pkey $rport 0.0.0.0
	echo "$response"
    fi
}

# TODO prettify this
iptables -L -v|grep dpt:$STARTPORT|grep tcp|grep $WAN |grep -q ACCEPT || iptables -A INPUT -i $WAN -p tcp --dport $STARTPORT -j ACCEPT
iptables -L -v|grep udp |grep $WAN|grep $STARTPORT:$ENDPORT -q || iptables -A INPUT -i $WAN -p udp -m multiport --dports $STARTPORT:$ENDPORT -j ACCEPT
ip6tables -L -v|grep udp |grep $WAN|grep $STARTPORT:$ENDPORT -q || ip6tables -A INPUT -i $WAN -p udp -m multiport --dports $STARTPORT:$ENDPORT -j ACCEPT

rm -f /tmp/wg-broker
mkfifo /tmp/wg-broker
rm -f /var/lock/${0##*/}

{
    while true
    do
	for i in $(get_wg_interfaces)
	do
	    prune_ifs $i
	done
	sleep 300
    done
} &

{
while [[ -z $EXITING ]]
do
    cat /tmp/wg-broker | handle_connection | nc -w 1 -l $BROKERPORT > /tmp/wg-broker
done
} &

wait
